#spring.data.elasticsearch.cluster-name=jiayin-2qi-es
#spring.data.elasticsearch.cluster-nodes=192.168.12.139:5100
#spring.data.elasticsearch.repositories.enabled=true

httpHost.host=192.168.12.133
httpHost.port=8200
httpHost.schema=http
esclient.connectNum=50
esclient.connectPerRoute=10


datasource.tyy.driver-class-name=com.mysql.cj.jdbc.Driver
datasource.tyy.url=jdbc:mysql://127.0.0.1:3306/tyy?serverTimezone=GMT%2B8&characterEncoding=utf-8&useSSL=false
datasource.tyy.username=root
datasource.tyy.password=zkhz123
datasource.tyy.testWhileIdle=true
datasource.tyy.validationQuery=select 1
datasource.tyy.timeBetweenEvictionRunsMillis=1800000