
jpa.hibernate.ddl-auto=none
spring.jpa.database-platform=org.hibernate.dialect.MySQL5Dialect
spring.jpa.open-in-view=false
spring.jpa.show-sql=false



datasource.test1.driver-class-name=net.sf.log4jdbc.DriverSpy
datasource.test1.url=jdbc:log4jdbc:mysql://localhost:3306/test1?serverTimezone=Asia/Shanghai&characterEncoding=utf-8&useSSL=false
datasource.test1.username=root
datasource.test1.password=zkhz123
datasource.test1.testWhileIdle=true
datasource.test1.validationQuery=select 1
datasource.test1.timeBetweenEvictionRunsMillis=1800000

datasource.test2.driver-class-name=com.mysql.cj.jdbc.Driver
datasource.test2.url=jdbc:mysql://localhost:3306/test2?serverTimezone=Asia/Shanghai&characterEncoding=utf-8&useSSL=false
datasource.test2.username=root
datasource.test2.password=zkhz123
datasource.test2.testWhileIdle=true
datasource.test2.validationQuery=select 1
datasource.test2.timeBetweenEvictionRunsMillis=1800000


n=20
